root: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json

plugins:
  - react
  - react-hooks
  - '@typescript-eslint/eslint-plugin'

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier

env:
  browser: true
  es6: true

settings:
  react:
    version: detect

globals:
  React: true
